### ISSUE TITLE
Create homebrew formula

### ISSUE THREAD

**Issue by lgarron** [lgarron/folderify#23]

**Comment by harens** [comment]
Sorry I'm a few years late. After seeing the current install instructions, I thought it might be simpler if there was a brew tap available (which I've created [here](https://github.com/harens/homebrew-folderify)).

folderify can then be updated whenever `brew update` is run, and imagemagick is automatically installed.

```shell
brew tap harens/folderify
brew install folderify
```
I am more than happy to transfer ownership to yourself if you're happy with it.

**Comment by lgarron** [comment]
That's neat! Do you know if this is the kind of thing that Homebrew itself would accept?

**Comment by harens** [comment]
There's various criteria that the formula and folderify itself will have to meet (such as the [following](https://docs.brew.sh/Acceptable-Formulae)) but there's certainly no harm in trying and I'll give it my best shot! 

I'll send a PR over to them once I think the formula is ready, and I'd be really grateful if you could take a look at the issue I raised here https://github.com/lgarron/folderify/issues/42 to help speed things up. Thanks

**Comment by harens** [comment]
I sent a PR over to them: https://github.com/Homebrew/homebrew-core/pull/58907, and it was approved! 🎉

The final result can be seen [here](https://github.com/Homebrew/homebrew-core/blob/4fbdc888bcd332fe1317e08b9cb99044348a3505/Formula/folderify.rb). Now, all you need to run is the following:

```
brew install folderify
```
I'm going to archive the [original tap](https://github.com/harens/homebrew-folderify), although you're still welcome to have it if you want. Thanks for your help!
