### ISSUE TITLE
Add option to export icns/iconset

### ISSUE THREAD

**Issue by stnvh** [lgarron/folderify#35]
Would be a very helpful feature, as currently the icons applied to the folders, although visible on the folder itself, appear as empty files (?) and no useable icon file is *actually* generated (only applied; contradicting the purpose of this program - to **generate** pretty, beveled OSX folder icons!)

![empty](https://cloud.githubusercontent.com/assets/6361200/6869545/e60890e8-d48c-11e4-93ad-3abc7f904ffa.png)

**Comment by lgarron** [comment]
Try running `folderify image.png` without a second argument. You should get an `image.iconset` folder and a `image.icns` file.

**Comment by stnvh** [comment]
Ah, I see, thanks.
