### ISSUE TITLE
Image appears background square (ImageMagick 7.0.5)

### ISSUE THREAD

**Issue by blasterbug** [lgarron/folderify#38]
As a result, I got this strange white shaded square where the icon of the folder appears. 
<img width="139" alt="folderify_white_stuff" src="https://cloud.githubusercontent.com/assets/891025/23343493/a2101c4e-fc6c-11e6-9972-435d02d94a75.png">

**Comment by lgarron** [comment]
It looks like your source image has more than one border – only the outermost one is removed.

What happens if you run `./f examples/src/octocat.png` on a checkout of the repo?
If that works, you'll probably want to edit your image to have a transparent background without borders.

**Comment by blasterbug** [comment]
Well, it does exactly the same.

**Comment by lgarron** [comment]
Hmm, it might be a a compatibility issue with ImageMagick, but... maybe not.

Any chance you can run (or ask someone to run) this on another Mac to see if they get the same result?

The OS version doesn't appear to be the problem, and any other information could be useful.

**Comment by blasterbug** [comment]
I am running imagemagick 7.0.5-0, installed with `brew`

**Comment by lgarron** [comment]
Thanks for that detail. I've upgraded to `imagemagick-7.0.5`, and I can reproduce.

**Comment by lgarron** [comment]
I don't know when I'll have time to fix this (I still have no idea how trivial it might be), but if you really want some folder images, I suggest downgrading to ImageMagick 6.9.6-5 temporarily.

**Comment by dardo82** [comment]
I’ve had the same problem but I’ve been able to solve it by downgrading ImageMagick with HomeBrew.
`brew uninstall imagemagick && brew install imagemagick@6 && brew link --force imagemagick@6`

**Comment by lgarron** [comment]
@blasterbug, @dardo82: would you mind verifying that the latest version of imagemagick works with the latest release of `folderify` for you?

**Comment by dardo82** [comment]
Does it work for you?

**Comment by lgarron** [comment]
> Does it work for you?

Yes, it does. Just want to make sure it works on more than my computer. :-)

**Comment by dardo82** [comment]
If I try It again I’ll tell you if it does work or not, in the meanwhile I want to thank you for your good job!
