### ISSUE TITLE
Dark mode icons

### ISSUE THREAD

**Issue by lgarron** [lgarron/folderify#41]
macOS uses darker folder icons for dark mode. I don't think it's possible to set a dynamic icon for a folder that switches between them, but a user who has permanent dark mode might want to use it, and a daemon could also switch known folders at transition time.

**Comment by lgarron** [comment]
Note: on Big Sur, the dark icons are much more similar to the light icons.

**Comment by cfwongfreeman** [comment]
In Mojave, folder icon looks very different in two modes. A new option "-dark" may be very helpful.

**Comment by aria-7553** [comment]
this would be very useful, i don't think it'd be that hard to do assuming its just changing the icon files on which the user's image is engraved. i've tried to manually replace the icons at `/usr/local/Cellar/folderify/2.1.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.iconset` but it didnt seem to work even after using `python3 /usr/local/Cellar/folderify/2.1.1/libexec/lib/python3.9/site-packages/folderify/__main__.py` to invoke the program, maybe its hardcoded somehow? the difference is minimal on big sur but because of my dock layout i have a custom folder right next to the the pictures folder and its slightly infaturating. i could commit to it but i dont know anything about the repo soo.. also changing the icons between dark and light mode *should* be possible, just need to figure out how macos itself does it and kinda trick it to do it for custom folders too but it might require SIP off or something so idk

**Comment by lgarron** [comment]
Copying from an email:

> It's definitely possible to generate dark mode icons, and at some point I would like to: https://github.com/lgarron/folderify/issues/41
> It's a little tricky, though, because users can switch from dark to light (automatically or manually) and I'm not aware of an easy way to switch file icons automatically. But we can at least generate the icons.
> 
> I don't know when I would get around to it, but I could use help:
> - Getting the dark mode template folders from the OS.
> - Tweaking the hardcoded colors in https://github.com/lgarron/folderify/blob/ffe32ceb9971d3e611ce4887cfe644614b458766/folderify/__main__.py#L210-L222
> - Adding and using a `--color-scheme` flag. (Fortunately, it's easy to support a "current system" value using `defaults read -g AppleInterfaceStyle`).

> i've tried to manually replace the icons at `/usr/local/Cellar/folderify/2.1.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.iconset`

Ooh, where did you get the icons?

I've had trouble extracting the dark folder icons from anywhere on Big Sur.

**Comment by lgarron** [comment]
> i've tried to manually replace the icons at `/usr/local/Cellar/folderify/2.1.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.iconset`

Ooh, where did you get the icons?

I've had trouble extracting the dark folder icons from anywhere on Big Sur.

**Comment by lgarron** [comment]
Looks like there are some versions at https://github.com/niem94/big-sur-folder-icons

@niem94, would you be willing to share how you found these?
(I'd like to extract them directly from the source to make 100% sure I have the right ones. There can be subtle color differences in conversion.)

**Comment by lgarron** [comment]
Aha!

https://github.com/insidegui/AssetCatalogTinkerer can extract files from `/System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/Resources/Assets.car`

It took me a while, but I found that info at https://developer.apple.com/forums/thread/657230?answerId=661120022#661120022

Thanks, @insidegui!

**Comment by lgarron** [comment]
> I don't think it's possible to set a dynamic icon for a folder that switches between them, but a user who has permanent dark mode might want to use it, and a daemon could also switch known folders at transition time.

I've filed #48 for that.

I'm closing this issue now that dark mode is implemented!

**Comment by niem94** [comment]
> Aha!
> 
> 
> 
> https://github.com/insidegui/AssetCatalogTinkerer can extract files from `/System/Library/PrivateFrameworks/IconFoundation.framework/Versions/A/Resources/Assets.car`
> 
> 
> 
> It took me a while, but I found that info at https://developer.apple.com/forums/thread/657230?answerId=661120022#661120022
> 
> 
> 
> Thanks, @insidegui!
> 
> 

Thanks for sharing this. I've been asked a few times how i did it, but had forgotten in the meantime, and work have gotten in the way for me to research it a new. I will refer people to this answer :-)

**Comment by aria-7553** [comment]
> > i've tried to manually replace the icons at `/usr/local/Cellar/folderify/2.1.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.iconset`
> 
> Ooh, where did you get the icons?
> 
> I've had trouble extracting the dark folder icons from anywhere on Big Sur.

i just used image2icon lol your source seems more reliable but i dont think the program actually uses those files anyway? idk bc the folder colours are still a little different

![Screenshot 2021-02-17 at 10 06 34 AM](https://user-images.githubusercontent.com/63844037/108168136-d8be6c00-7107-11eb-8cee-fba7408ab244.png)

**Comment by lgarron** [comment]
> i just used image2icon lol your source seems more reliable but i dont think the program actually uses those files anyway? idk bc the folder colours are still a little different
> 
> ![Screenshot 2021-02-17 at 10 06 34 AM](https://user-images.githubusercontent.com/63844037/108168136-d8be6c00-7107-11eb-8cee-fba7408ab244.png)

It looks like you're still using a light mode icon. Could you make sure you're on folderify `v2.2.0` or later, and generate an icon using `--color-scheme dark`?

**Comment by aria-7553** [comment]
> > i just used image2icon lol your source seems more reliable but i dont think the program actually uses those files anyway? idk bc the folder colours are still a little different
> > ![Screenshot 2021-02-17 at 10 06 34 AM](https://user-images.githubusercontent.com/63844037/108168136-d8be6c00-7107-11eb-8cee-fba7408ab244.png)
> 
> It looks like you're still using a light mode icon. Could you make sure you're on folderify `v2.2.0` or later, and generate an icon using `--color-scheme dark`?

`convert: unable to open image '/usr/local/Cellar/folderify/2.2.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.dark.iconset/icon_16x16.png': No such file or directory @ error/blob.c/OpenBlob/3537.`
i didnt notice that folder either, just two versions of yosemite and one big sur
but i tried to replace them with the files i got from the assets, generate it again, and it seems to have worked, except the grave is a little lighter than normal, despite the image being pure black over transparent 

![Screenshot 2021-02-17 at 10 39 56 AM](https://user-images.githubusercontent.com/63844037/108171379-7ddb4380-710c-11eb-834f-bad1bb6ab830.png)

**Comment by lgarron** [comment]
> convert: unable to open image '/usr/local/Cellar/folderify/2.2.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.dark.iconset/icon_16x16.png': No such file or directory @ error/blob.c/OpenBlob/3537.

*shakes fist at Python*
I've tried publishing a fix in `v2.2.2` to PyPI. Let me know if that owrks.

> but i tried to replace them with the files i got from the assets, generate it again, and it seems to have worked, except the grave is a little lighter than normal, despite the image being pure black over transparent

Yeah, the dark icons have a darker main fill. `v2.2.2` should take care of that for Big Sur folders when you pass `--color-scheme dark`.

**Comment by aria-7553** [comment]
> > convert: unable to open image '/usr/local/Cellar/folderify/2.2.1/libexec/lib/python3.9/site-packages/folderify/GenericFolderIcon.BigSur.dark.iconset/icon_16x16.png': No such file or directory @ error/blob.c/OpenBlob/3537.
> 
> _shakes fist at Python_
> I've tried publishing a fix in `v2.2.2` to PyPI. Let me know if that works.
> 
> > but i tried to replace them with the files i got from the assets, generate it again, and it seems to have worked, except the grave is a little lighter than normal, despite the image being pure black over transparent
> 
> Yeah, the dark icons have a darker main fill. `v2.2.2` should take care of that for Big Sur folders when you pass `--color-scheme dark`.

oh yes it works now
i think they're p much the same tho, as expected, so i think the grave should be a little darker for dark mode

![Screenshot 2021-02-17 at 9 19 42 PM](https://user-images.githubusercontent.com/63844037/108249377-0df9a700-7166-11eb-9eff-11a6cace08b8.png)
