### ISSUE TITLE
License Consistency

### ISSUE THREAD

**Issue by harens** [lgarron/folderify#42]
I am currently working on a brew formula for folderify found [here](https://github.com/harens/homebrew-folderify).

When I audit it (in the hopes of adding it to [homebrew/core](https://github.com/Homebrew/homebrew-core)), I get the following error:

```shell
* License mismatch - GitHub license is: [], but Formulae license states: ["MIT"].
```

I had set the license to MIT since this is what is stated on the [PyPi project description](https://pypi.org/project/folderify/). If I don't set a license, the audit also complains.

```shell
* No license specified for package.
```

**Comment by lgarron** [comment]
What does this require? Just a license file?

**Comment by harens** [comment]
I think so. Then it should be good.

**Comment by lgarron** [comment]
d4e91520a58fbf1c6c1196ed95517513d07be6ba
 should help!

**Comment by harens** [comment]
Thanks! It has fixed this issue.
