### ISSUE TITLE
ImportError: No module named folderify.__main__

### ISSUE THREAD

**Issue by blasterbug** [lgarron/folderify#46]
After installing on Big Sur from brew and running the command for instance `folderify ~/Downloads/octocat.png ~/GitHub` I got the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/folderify", line 7, in <module>
    from folderify.__main__ import main
ImportError: No module named folderify.__main__
```

**Comment by lgarron** [comment]
Hmm, I can't really make sense of that error, and I was able to install. Could you try `brew reinstall folderify`?

**Comment by blasterbug** [comment]
(Sorry for the slow abswer) I did try before opening the issues and I tried again before replying and still the same error.
