### ISSUE TITLE
Bad interpreter error

### ISSUE THREAD

**Issue by tishbanks** [lgarron/folderify#56]
bad interpreter: /usr/local/Cellar/folderify/2.3.0/libexec/bin/python3.9: no such file or director

Don't know what's going on. Ty

**Comment by lgarron** [comment]
Sure sounds like `python3.9` is not installed, and looks like you tried to install using Homebrew.

[Could you try ](https://github.com/Homebrew/homebrew-core/blob/38a8f2a582293b3013608c97785338bbb8a2d841/Formula/folderify.rb#L23) should automatically install `python3.9`; what are the chances you might have uninstalled it? 

`brew install python@3.9` might get you back into a good state. If not, does `brew uninstall folderify` followed by `brew install folderify` help?

**Comment by lgarron** [comment]
Closing this out for now; please comment if you're still having issues!
