### ISSUE TITLE
Small Icon Image Issue

### ISSUE THREAD

**Issue by martinpradojr** [lgarron/folderify#57]
The small icon_16x16 image has what appears to be a white shadow artifact. It's noticeable when Finder is in List or Columns view. If I manually copy the images and paste them in the icon within the Get Info panel, I don't see it though. The 16x16 ends up being too small and blurry, based on that I'm not sure what's causing it. The shadow artifact is the same though.

![folderify-small-icon](https://user-images.githubusercontent.com/16161288/152375154-a89eb980-17da-4d3c-b6b1-369b4e17fb3e.png)

From the image, both the folder icon in Column view on the left and the selected 16x16 icon have the white shadow artifact.

**Comment by lgarron** [comment]
Thanks for filing this!

This is kind of low priority, but I intend to take a look at some point.

**Comment by lgarron** [comment]
Well, this should help.

![Screen Shot 2022-03-17 at 17 01 38](https://user-images.githubusercontent.com/248078/158912858-aa4017be-f9e4-4f79-aa80-c01a28cbc115.png)

Apple's own icons at 16x16@1x are actually quite bad:

![Screen Shot 2022-03-17 at 17 02 02](https://user-images.githubusercontent.com/248078/158912931-f1b42f65-7872-4cd6-9f8e-5fc293ea9f34.png)

So I'd say we're actually doing better, although it might be worth cranking up the contrast in the future.

**Comment by lgarron** [comment]
Alright, mind trying `v2.3.1`?

**Comment by lgarron** [comment]
Going to close this out, please let me know if you still see any issues!
