### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by giomacias** [lgarron/folderify#60]
Hi Lucas!

Just dropping a quick thank you note! OCD set in and I decided to make some folders. I came across your awesome tool. Simple and they look fantastic. 

Many thanks!
Gio

<img width="774" alt="folderify1" src="https://user-images.githubusercontent.com/19860629/172018543-9f135854-98f4-49a6-8086-72ff506d53dc.png">
<img width="322" alt="folderify2" src="https://user-images.githubusercontent.com/19860629/172018547-809063bf-dbca-4336-90a1-bb9be491136b.png">

**Comment by lgarron** [comment]
Oooh, thanks, these were really lovely to see! 😻
