### ISSUE TITLE
Create a variation to generate new file styles on paper txt, like below

### ISSUE THREAD

**Issue by artking28** [lgarron/folderify#61]
Hey bro, i've seen your project, its amazing, you could add new features, the first one that comes on my mind is to turns PNG's, ICNS and SVG's into default apple text file. It would be so cool, like below

![goPure](https://user-images.githubusercontent.com/78158057/174887841-79ad2e9e-db15-411a-8d04-876df953381a.png)

Turns a default IOS icon 

![go-original-wordmark_1](https://user-images.githubusercontent.com/78158057/174887887-91b7951f-02f2-496c-a117-a1a20028645d.png)

**Comment by lgarron** [comment]
Hmm, sorry, I thought I commented on this issue but apparently I missed it until now. 😕

For the time being, I would consider this out of the scope of the project. As the name suggests, `folderify` is focused specifically on the folder-specific styling.

If you need, I could probably figure out a 1-line command to generate file icons like yours, although it should also be easy to do by hand in any raster editor.
