### ISSUE TITLE
Icons reverting to plain folders?

### ISSUE THREAD

**Issue by acstadermann** [lgarron/folderify#62]
Not sure if this is an issue with folderify or with Mac but perhaps someone here knows a solution.

I used folderify a week or two ago and changed some of my folder icons, but they seem to revert back to the standard/default folder icon after some period of time. It happened when I restarted, but also just randomly after a handful of days (after waking from sleep).

Anyone know what's going on, what I'm doing wrong, or what the problem is?

Thanks!

**Comment by lgarron** [comment]
I haven't heard of this issue from anyone else. Is it possible that something is touching or re-creating these icons. Are there particular paths that are affected?

**Comment by acstadermann** [comment]
Thanks, I wonder what I'm doing that's messing it up. I have the folders as shortcuts in my dock, but the actual location of the folders is under Documents (icons revert in both dock and finder). I use Google Drive as a backup for Documents, perhaps that is somehow affecting things. I'll try customizing a folder outside of the backup & see what happens.

If it is the Google Drive backup, how would I go about fixing that? Would I contact Google Drive support, since it's probably on their end?

**Comment by lgarron** [comment]
> If it is the Google Drive backup, how would I go about fixing that? Would I contact Google Drive support, since it's probably on their end?

Yeah, it sounds quite plausible that Google Drive is doing that, as most (all?) sync services ignore resource forks.

(Also, fun fact: the Google Drive folder icon on macOS was also made using `folderify`.)

**Comment by acstadermann** [comment]
Concluding remarks: The folder that is backed up by Google Drive reverted to the standard folder, the non-backed up folder remained customized. I found this Google Drive Backup help post that I think fixes the issue, for anyone that may have the same issue in the future: https://support.google.com/drive/thread/125430240?hl=en&msgid=128865125
