### ISSUE TITLE
Custom base icon

### ISSUE THREAD

**Issue by dardo82** [lgarron/folderify#63]
Can you add an option to use a different generic folder on which then apply the masks to personalise it more?

**Comment by lgarron** [comment]
Do you have an idea of how this would work?

The embossing layout is very carefully tuned to each icon, and that is not something I want to turn into an API surface.

If someone wants to tune the icon, you can always run from source: https://github.com/lgarron/folderify#download-the-source-code-directly

**Comment by dardo82** [comment]
It would work normally, just with a different texture or
color on the base icon, keeping the layout the same...

**Comment by dardo82** [comment]
Thanks for the quick reply, but where is the issue here?
It would work normally, just with a different texture or
color on the base icon, keeping the layout the same.

**Comment by lgarron** [comment]
> keeping the layout the same.

This is the part that really work. The purpose of this project is to produce perfectly aligned folder icons tailored specifically to various macOS folder icons at various resolutions.

An alternate background would need a set of source images that match the exact same dimensions at each resolution.

One possibility might be the option to change the *hue* of the folder, similar to how macOS does purple smart folders. Does that match what you're asking for?

**Comment by dardo82** [comment]
> Does that match what you're asking for?

No,but it would still be an improvement...


> At that point, you're better off using an image editor to do it manually.

No but given that you aren't willing to help I'll do it by
myself,replacing the stock iconset with a custom one.


The project is open source,but you aren't open to hear
suggestions to make it better,so what's the point of it?

**Comment by dardo82** [comment]
> Does that match what you're asking for?

No, but it would still be an improvement...


> At that point, you're better off using an image editor to do it manually.

No but given that you aren't willing to help I'll do it by
myself, replacing the stock iconset with a custom one.


The project is open source, but you aren't open to hear
suggestions to make it better, so what's the point of it?

There are no real technical limitations, unlike you are
trying to suggest, given that you are already doing it
with the various OS versions, you are just stubborn...

I was here to HELP you improve YOUR work, but you 
(like many people sadly) are unable to collaborate in
a productive way and prefer to find absurd excuses...

This way you will not get very far in your lonely life son,
but I'm not your father (unlike the famous movie quote)
so I can only give you an hand if you give me your, ok?

**Comment by dardo82** [comment]
...
