### ISSUE TITLE
Default Icons

### ISSUE THREAD

**Issue by asoksevil** [lgarron/folderify#64]
Hi,

Would there be any kind souls who can create the default folder icons for applications, documents, downloads, movies, etc?

I just need the downloads folder one because after doing this: https://apple.stackexchange.com/questions/270227/how-to-sync-an-additional-folder-to-icloud-drive-similar-to-how-macos-sierra-doe

Basically this image: 
![](https://www.intego.com/mac-security-blog/wp-content/uploads/2021/03/download-folder-400.png)

![](https://www.intego.com/mac-security-blog/wp-content/uploads/2021/03/downloads-hero.png)

Many thanks!

**Comment by lgarron** [comment]
How do you need to use the icons. Any reason wouldn't be able to copy them directly from the relevant folders in your home directory?

**Comment by asoksevil** [comment]
I actually don’t know where the folder is and I don’t where it will be in the right format!

I think Monterey has a different style to previous versions and not sure if Ventura is the same!

**Comment by lgarron** [comment]
Hmm, I guess I'm not quite clear on your goal then. Are you trying to apply folder styles from a different OS version? Across computers? Or just transfer between folders on one computer?

Transferring folder icons is easiest using `Get Info` (⌘I) in Finder, where you can highlight the folder icon in the top left of the resulting pop-up and copy/paste to another info folder's pop-up.

**Comment by asoksevil** [comment]
What I am trying to do is very simple! I just would like to have access to all the default icons in a PNG or workable format and apply it to other icons!

My main issue now is that the download folder icon has changed into a generic folder icon because I’ve basically made it synced to iCloud so I would like to bring back the download folder icon back and I cannot find where I can get a “clean” version that also matches the current OS (Ventura) as Monterey and earlier versions which I’ve been able to find the icons don’t have a blank background that I can just copy and paste using the get info method you’ve said.

**Comment by lgarron** [comment]
In that case, does `/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/` have what you need?
