### ISSUE TITLE
Automatically convert SVG icons to a usable mask

### ISSUE THREAD

**Issue by bmFtZQ** [lgarron/folderify#65]
Use Inkscape (if installed) to automatically convert SVG icons to a PNG image to be used for the mask. If inkscape is installed using Homebrew Cask, then it should be linked to the `$PATH` variable automatically.

Inkscape syntax for exporting to a PNG image with a height of 1024px:

```sh
# -h option specifies image height in pixels
# -o option specifies output file
inkscape "input.svg" -h 1024 -o "output.png"
```

Using the output from Inkscape to create a folder icon:

![example mask icon](https://user-images.githubusercontent.com/62812711/210710507-f3b33a5d-d4c0-488f-852c-f048ce8233db.png)

Here is the original SVG:
![example svg](https://user-images.githubusercontent.com/62812711/210709924-dcac8121-b122-48b1-a51f-dfe634669c3f.svg)

**Comment by lgarron** [comment]
Hmm, it looks like `convert` works with SVGs, but doesn't handle opacity correctly.

I don't want to add required dependencies if it can be avoided, and optional dependencies can be tricky as well.

It looks like you already know how to use Inkscape to process icons into PNG. Is there any particular reason you need the functionality built-in?

**Comment by bmFtZQ** [comment]
It would just be a nice to have feature, as I would only need to run one command to create the full icon after creating the SVG file. I just thought it would be easier to use Inkscape directly, using ImageMagick would work but there are two issues:

 * When an SVG image is input into Folderify, it uses the default background colour (white). But this is an easy fix, specify `-background: none` or `-background: transparent` before the input file:

```sh
# important for the -background option to come before the svg input file
convert -background none input.svg output.png
```

 * There isn't an easy way to properly specify an image output size, only the density (which scales the image):

```sh
# default density is 96
convert -background none -density 96 input.svg output.png
```

Specifying an image size using `-size` or `-resize` will either do nothing, or will produce pixelated results when scaling to a resolution higher than the SVG file dimensions.

But since the default density is 96, a new image size can be calculated.

The formula to calculate the density to resize an image to a specific height would be something like this:

```
96 / ORIGINAL_HEIGHT * NEW_HEIGHT
```

The original height of the image can be obtained using ImageMagick's identify command:
```sh
identify -format '%h' "input.svg"
```

**Comment by lgarron** [comment]
> * When an SVG image is input into Folderify, it uses the default background colour (white). But this is an easy fix, specify `-background: none` or `-background: transparent` before the input file:
> 

Aha! It looks like somehow this ended up out of order in the current code. I'm pretty sure SVGs used to work just fine, so that explains it. Please let me know if `v2.3.2` works for you!

**Comment by bmFtZQ** [comment]
The SVG file still only renders at the original dimensions, so this SVG file only gets rendered at 64x64 pixels, then scaled up to the size needed for the icon, leaving a blurry/pixelated result:

![pixelated icon](https://user-images.githubusercontent.com/62812711/210915013-c20560af-c148-41bd-86ea-e340f7d10e20.png)

What the image should look like:
![icon_512x512](https://user-images.githubusercontent.com/62812711/210915659-c253a6dc-ca03-4f06-b6cd-ac27bc0bc9cf.png)

**Comment by lgarron** [comment]
Ah, I see, you're saying this happens for tiny SVGs with a lot of detail?

We do scale the image to compensate for that, but I guess it's happening after rasterization. Let me hack with the density command like you suggest.

**Comment by bmFtZQ** [comment]
> Ah, I see, you're saying this happens for tiny SVGs with a lot of detail?

Yes, ImageMagick only seems to scale the image after rasterisation, causing the image to only use the original dimensions of the SVG file, in my case 64x64 pixels. The `-density` option will scale the image before rasterisation, resulting in a higher resolution image.

The `-density` option also changes the image DPI, but I don't think that should effect the mask, since it will be overlayed on to the folder icon anyway.

**Comment by lgarron** [comment]
> * There isn't an easy way to properly specify an image output size, only the density (which scales the image):
> 
> ```shell
> # default density is 96
> convert -background none -density 96 input.svg output.png
> ```
> 
> Specifying an image size using `-size` or `-resize` will either do nothing, or will produce pixelated results when scaling to a resolution higher than the SVG file dimensions.

I'm still struggling with this I'm reluctant to read the image size and do calculations based on that, but it seems you're right and there's no way around it. :-/

**Comment by lgarron** [comment]
This seems to be working well for now. It's not perfect, as small icons can still get quantized:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><circle cx="5" cy="5" r="3" fill="transparent" stroke="black" stroke-width="2" /></svg>
```
![icon_512x512@2x](https://user-images.githubusercontent.com/248078/229759726-9cc00a3a-f5ac-43e3-b8f0-c084f3d98ab5.png)

But I think that's out of scope to fix.
