### ISSUE TITLE
Homebrew not upgrading folderify formula after v2.4.0

### ISSUE THREAD

**Issue by xilopaint** [lgarron/folderify#69]
The latest Homebrew version is v2.4.0:

```
$ brew upgrade folderify
Warning: folderify 2.4.0 already installed
```

**Comment by lgarron** [comment]
Hmm thanks for letting me know. I also had this issue and assumed it was something in my local setup, but now I'm more wary. It *could* also be caching & rate limiting on the API.

Could you try removing `/Users/lgarron/Library/Caches/Homebrew/api/` and see what happens?

**Comment by xilopaint** [comment]
No need to `rm -rf ~/Library/Caches/Homebrew/api/`, I just ran `brew upgrade folderify` again and it installed v3.0.7.

**Comment by lgarron** [comment]
> No need to `rm -rf ~/Library/Caches/Homebrew/api/`, I just ran `brew upgrade folderify` again and it installed v3.0.7.

I'm going to assume that this was a caching issue for you and me. Closing for now.
