### ISSUE TITLE
Option to Add Alias Icon to Output 

### ISSUE THREAD

**Issue by Avakining** [lgarron/folderify#71]
I'd like if there was an option to make the output icon include the little alias arrow, as changing the icon of the original folder doesn't change the icons for aliases.

**Comment by lgarron** [comment]
Hmm, interesting. I would have assumed that the arrow is an overlay, but it does in fact seem to be part of the generated icon itself.

This shouldn't be too hard to add, although I'll have to think about the API.

**Comment by lgarron** [comment]
Okay, I was able to implement it, but the assigned icon doesn't seem to work: https://github.com/lgarron/folderify/commit/2342da8c7a1f2ae5fb280ec4c2fa2a42f2512e90

<img width="154" alt="Screenshot 2023-04-22 at 19 56 00" src="https://user-images.githubusercontent.com/248078/233817096-7dfbd8df-161c-4aac-a5e3-2d3b513ed2b3.png">

**Comment by lgarron** [comment]
Available in `v3.2.0`.
