### ISSUE TITLE
Incorrect icons when using `Rez` for assignment

### ISSUE THREAD

**Issue by rktprof** [lgarron/folderify#75]
The folder icons were updated at some point, so when creating icons for macOS Ventura the icons doesn't look right

Here is an example of a generated icon on the left and a standard icon on the right (from two Get Info windows)
![Screenshot 2023-09-04 at 11 41 34](https://github.com/lgarron/folderify/assets/56829534/10e93f54-4865-48e9-b69c-be30e94f7c37)

**Comment by lgarron** [comment]
Hmm, there are a couple of potential reasons you could be seeing a difference in icons. Could I ask you to upload and share the `.iconset` of your icon when it's not assigned to a folder?

```shell
folderify

**Comment by rktprof** [comment]
Interesting, after some more testing it seems to only happen when using direct assignment to a folder:

```
folderify /path/to/mask/godot.png /path/to/target/folder
folderify --output-iconset /path/to/output/godot.iconset /path/to/mask/godot.png /path/to/target/folder
```

gives me the incorrect icon assigned to the target folder, but the output iconset seems to be correct 
[godot dark.iconset.zip](https://github.com/lgarron/folderify/files/12520735/godot.dark.iconset.zip)
[godot light.iconset.zip](https://github.com/lgarron/folderify/files/12520742/godot.light.iconset.zip)
[godot mask](https://github.com/lgarron/folderify/assets/56829534/40e55c54-a44a-41a1-9035-96fe3072ca6f)

I'm running macOS 13.4 Dark mode on an M1 Max Macbook Pro, installed folderify using Homebrew

**Comment by lgarron** [comment]
Okay, I suspect this is an issue with the icon assignment, possibly related to https://github.com/lgarron/folderify/issues/71#issuecomment-1518927085

It might be worth looking at https://github.com/sveinbjornt/osxiconutils again.

I don't know when I'll have time to look into this, but I definitely want to get to the bottom of it.

**Comment by Eejit43** [comment]
I'm experiencing this issue as well when using the direct assignment to a folder. Any workarounds?

**Comment by Eejit43** [comment]
> I'm experiencing this issue as well when using the direct assignment to a folder. Any workarounds? It is a minor difference but it is bugging me a bit

Seems like the program only detects versions up to Big Sur (11.0), is that intended?

**Comment by Eejit43** [comment]
@lgarron instead of osxiconutils, https://github.com/mklement0/fileicon seems to work like a charm! Folder looks correct when using that, aside from barely noticeable shading change on the bottom of the folder (but that's a different issue I believe).

**Comment by Opa-** [comment]
I've noticed some color difference too, especially noticeable in columns mode :
![image](https://github.com/lgarron/folderify/assets/6153672/cb593e28-799b-4710-88e7-274888ae17a3)

Using folderify 3.0.13 with Ventura 13.6.3 (22G436)

Here's a zip containing the input png and the generated iconset if that helps [iconset.zip](https://github.com/lgarron/folderify/files/13658023/iconset.zip)
