### ISSUE TITLE
Help with Folderify?

### ISSUE THREAD

**Issue by GNHRMN** [lgarron/folderify#77]
Hey — I am unfamiliar with the macOS terminal and how to use it. I managed to download Homebrew and then in the terminal I downloaded Folderify. I can't seem to be able to execute the code to actually get the png onto the image. Any chance you could help?

**Comment by lgarron** [comment]
If you already have Homebrew install, it should be pretty simple:

```shell
brew install folderify
folderify [path to image file] [path to folder]
```

You can drag the file and folder into the terminal. Here's a screencap:

https://github.com/lgarron/folderify/assets/248078/d7d19551-fe00-4af3-85b7-27454b1b8473

Do those steps work for you?
