### ISSUE TITLE
Add option change directory color and set style all sub-directory

### ISSUE THREAD

**Issue by boyseez** [lgarron/folderify#79]
Is it possible to add color to a directory?

Is it possible to set the style of subdirectories of a parent folder?

**Comment by lgarron** [comment]
Could you specify what this looks like?

https://github.com/lgarron/folderify/issues/72 tracks adding folder icon coloring, and I'm not aware of any relevant macOS features for this.

If you want to apply a particular folder icon to all folders in a tree, this could be *very* inefficient, and I doubt I would implement it in `folderify` directly. You should be able to do it easily with a script, though.

**Comment by lgarron** [comment]
> You should be able to do it easily with a script, though.

Here's an example script in `fish` that assigns the same icon to all nested folders in the current path:

```fish
brew install folderify fileicon
folderify icon.png
for FOLDER in (find . -type d)
  fileicon set $FOLDER icon.icns
end
```
