### ISSUE TITLE
zsh: command not found: brew

### ISSUE THREAD

**Issue by whoisgrayson** [lgarron/folderify#81]
I have installed Homebrew and am now trying to install Folderify by using this:

`brew install folderify`

but it keeps saying 

`zsh: command not found: brew`

Anyone know what I am doing wrong? Thanks!

**Comment by lgarron** [comment]
Sounds like `brew` is not in your `$PATH`.

I suggest consulting https://brew.sh/ and https://github.com/Homebrew/brew/issues for information.
