### ISSUE TITLE
Restore the macOS 13 runner

### ISSUE THREAD

**Issue by lgarron** [lgarron/folderify#85]
See https://github.com/lgarron/folderify/commit/5ca16b98ea9df235e334f5ba201386d49f44ff5d

**Comment by lgarron** [comment]
https://github.com/lgarron/folderify/commit/23cef0e7ed1b1dd015b06669393445c6083f5157 didn't help. The job has been queued for over 8 hours.

**Comment by craig65535** [comment]
Is it supposed to say `macsos-13`? Looks like a typo.

**Comment by lgarron** [comment]
> Is it supposed to say `macsos-13`? Looks like a typo.

Ah, thanks, I typed that one manually!

A bit funky that this didn't cause the job to fail immediately. 😳

**Comment by lgarron** [comment]
The runner is still failing. I've filed https://github.com/Homebrew/brew/issues/16930
