### ISSUE TITLE
16x16 folder icons very low quality

### ISSUE THREAD

**Issue by t3rminus** [lgarron/folderify#86]
I used folderify to add a "no entry" sign to a folder. Most sizes look good! But the 16x16px size looks off, and the little jaggy opaque corners and weird "glow" line at the bottom of the image are catching my attention and tripping me up. See attached screenshot.

Any help would be appreciated!

Generated on M3 MBP, Sonoma 14.4.1

![image](https://github.com/lgarron/folderify/assets/643473/56f32235-a41c-4551-8419-28dc4a8ebdd0)

**Comment by lgarron** [comment]
That looks like you're using a very old version of `folderify`. What version are you running?

**Comment by t3rminus** [comment]
> % folderify --version
> folderify 3.2.4

Just installed today using `brew install folderify`

**Comment by lgarron** [comment]
Hmm, would you mind sharing your mask file and output `.iconset` images? I can take a closer look.

**Comment by t3rminus** [comment]
Here's the mask image, iconset, and icns file.
![1](https://github.com/lgarron/folderify/assets/643473/178bc47f-a713-4cd3-b397-f67fcbb8ea37)
[1.iconset.zip](https://github.com/lgarron/folderify/files/15475446/1.iconset.zip)
[1.icns.zip](https://github.com/lgarron/folderify/files/15475507/1.icns.zip)

It's strange... the iconset looks fine, but the resulting icns file looks weird in preview (the sidebar thumbnails are yellow instead of blue, although clicking on the thumbnail seems to display it correctly).

![image](https://github.com/lgarron/folderify/assets/643473/d388f414-7366-4f54-b035-ec602cd3ea9d)

I also want to note that I wasn't able to reproduce this on my built-in mac display, or my 4K Dell monitor at home. It only seemed to be an issue when generating icons on my 1080p ASUS monitor at the office. Maybe it has to do with the active display colorspace or calibration at the time the icon is generated?

**Comment by t3rminus** [comment]
Second note:
This issue only seems to occur when running the command `folderify 1.png` to generate the icns first, then copy+pasting or dragging+dropping it into the icon slot in the Get Info window of a file/folder.

It does not seem to occur when doing `folderify 1.png /path/to/dest`.

**Comment by lgarron** [comment]
Yeah, there are all sorts of subtle details when it comes to resource forks and icons. 😢

I don't think there's much for `folderify` to do, as setting the icon directly is core functionality. If enough people run into this, we can consider adding caution message when `folderify` is invoked without a target.

If you personally need to to assign `.icns` icons often, I suggest installing https://formulae.brew.sh/formula/fileicon or using `osascript`: https://formulae.brew.sh/formula/fileicon
