### ISSUE TITLE
WARNING: The `convert` command is deprecated in IMv7, use "magick"

### ISSUE THREAD

**Issue by philsherry** [lgarron/folderify#87]
As of roughly this week(?), I've started getting this error message when using folderify. (I have v3.2.4)

> WARNING: The convert command is deprecated in IMv7, use "magick"

I had a quick look to see if anyone else had reported it, but couldn't find anything… which always makes me second-guess if I'm in the right place to report something. 

Anyway, here's some install info for you. Wasn't sure what you might need, but I've guess at these three things for starters. Let me know if you need anything else. 

<details>
  <summary>brew info folderify</summary>
  <pre><code>&gt; ==&gt; folderify: stable 3.2.4 (bottled), HEAD&#10;Generate pixel-perfect macOS folder icons in the native style&#10;https://github.com/lgarron/folderify&#10;Installed&#10;/opt/homebrew/Cellar/folderify/3.2.4 (10 files, 3.7MB) *&#10;  Poured from bottle using the formulae.brew.sh API on 2024-04-26 at 13:30:48&#10;From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/f/folderify.rb&#10;License: MIT&#10;==&gt; Dependencies&#10;Build: rust &#10004;&#10;Required: imagemagick &#10004;&#10;==&gt; Requirements&#10;Build: Xcode (on macOS) &#10004;&#10;Required: macOS &#10004;&#10;==&gt; Options&#10;--HEAD&#10;        Install HEAD version&#10;==&gt; Caveats&#10;zsh completions have been installed to:&#10;  /opt/homebrew/share/zsh/site-functions&#10;==&gt; Analytics&#10;install: 184 (30 days), 1,001 (90 days), 3,814 (365 days)&#10;install-on-request: 184 (30 days), 1,001 (90 days), 3,814 (365 days)&#10;build-error: 0 (30 days)&#10;</code></pre>
</details>

<details>
  <summary>brew info imagemagick</summary>
  <pre><code>==&gt; imagemagick: stable 7.1.1-33 (bottled), HEAD&#10;Tools and libraries to manipulate images in many formats&#10;https://imagemagick.org/index.php&#10;Installed&#10;/opt/homebrew/Cellar/imagemagick/7.1.1-33 (808 files, 32.3MB) *&#10;  Poured from bottle using the formulae.brew.sh API on 2024-05-28 at 14:25:28&#10;From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/i/imagemagick.rb&#10;License: ImageMagick&#10;==&gt; Dependencies&#10;Build: pkg-config &#10004;&#10;Required: fontconfig &#10004;, freetype &#10004;, ghostscript &#10004;, jpeg-turbo &#10004;, jpeg-xl &#10004;, libheif &#10004;, liblqr &#10004;, libpng &#10004;, libraw &#10004;, libtiff &#10004;, libtool &#10004;, little-cms2 &#10004;, openexr &#10004;, openjpeg &#10004;, webp &#10004;, xz &#10004;, gettext &#10004;, glib &#10004;, imath &#10004;, libomp &#10004;&#10;==&gt; Options&#10;--HEAD&#10;        Install HEAD version&#10;==&gt; Analytics&#10;install: 75,431 (30 days), 224,282 (90 days), 891,119 (365 days)&#10;install-on-request: 69,223 (30 days), 208,062 (90 days), 821,747 (365 days)&#10;build-error: 23 (30 days)</code></pre>
</details>

<details>
  <summary>brew --config</summary>
  <pre><code>HOMEBREW_VERSION: 4.3.2&#10;ORIGIN: https://github.com/Homebrew/brew&#10;HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530&#10;Last commit: 2 days ago&#10;Core tap JSON: 28 May 16:08 UTC&#10;Core cask tap JSON: 28 May 16:08 UTC&#10;HOMEBREW_PREFIX: /opt/homebrew&#10;HOMEBREW_REPOSITORY: /opt/homebrew/Homebrew&#10;HOMEBREW_BAT: set&#10;HOMEBREW_BAT_THEME: tokyonight_night&#10;HOMEBREW_CASK_OPTS: [&quot;--fontdir=/Library/Fonts&quot;]&#10;HOMEBREW_CLEANUP_MAX_AGE_DAYS: 5&#10;HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3&#10;HOMEBREW_DISPLAY_INSTALL_TIMES: set&#10;HOMEBREW_EDITOR: code&#10;HOMEBREW_GITHUB_PACKAGES_TOKEN: set&#10;HOMEBREW_INSTALL_BADGE: &#129750;&#10;HOMEBREW_MAKE_JOBS: 10&#10;Homebrew Ruby: 3.3.1 =&gt; /opt/homebrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby&#10;CPU: 10-core 64-bit arm_firestorm_icestorm&#10;Clang: 15.0.0 build 1500&#10;Git: 2.45.1 =&gt; /opt/homebrew/bin/git&#10;Curl: 8.6.0 =&gt; /usr/bin/curl&#10;macOS: 14.5-arm64&#10;CLT: 15.3.0.0.1.1708646388&#10;Xcode: 15.4&#10;Rosetta 2: false</code></pre>
</details>

**Comment by lgarron** [comment]
Hmm, this is the first I've heard of `convert` being deprecated, thanks for the report. I'll have to see if `magick` is sufficiently widely available, or implement a fallback.

**Comment by lgarron** [comment]
It's a bit annoying to pin down when exactly ImageMagick introduced `magick`, and when they deprecated `convert`.

https://imagemagick.org/script/porting.php states that:

> The "magick" command is the new primary command of the Shell API, replacing the old "convert" command. This allows you to create a 'magick script' of the form "#!/path/to/command/magick -script", or pipe options into a command "magick -script -, as a background process.

But also that document is undated, and its own examples still use `convert`. 🤷

Indications on the internet are that the `magick` command was introduced at least ≈8 years ago, though.

**Comment by lgarron** [comment]
Looks like the `convert` command was marked as deprecated in the ImageMagick source 3 weeks ago: https://github.com/ImageMagick/ImageMagick/commit/75a5c6d168379dd6e74f207468444cb2cff11720

Which was merged into Homebrew 3 days ago: https://github.com/Homebrew/homebrew-core/pull/172824

**Comment by philsherry** [comment]
3 days ago, yeah that would track for me seeing it happen. 

Super-fast turnaround on this one, though. Nice one. 🙏🏻
